import { EventInput } from "@fullcalendar/core";

let eventGuid = 0;
let todayStr = new Date().toISOString().replace(/T.*$/, "");

export const INITIAL_EVENTS: EventInput[] = [
  {
    id: createEventId(),
    title: "Aurora Tech Conference",
    start: "2025-02-01",
    end: "2025-02-01T12:00:00",
    textColor: "#559cda",
    backgroundColor: "#deecff",
    extendedProps: { department: "IT" },
  },
  {
    id: createEventId(),
    title: "Pixel Innovators Meetup",
    start: "2025-02-01",
    textColor: "#ff554a",
    backgroundColor: "#ffcbc7",
    extendedProps: { department: "HR" },
  },
  {
    id: createEventId(),
    title: "NextGen AI Workshop",
    start: "2025-02-01",
    textColor: "#5a9d27",
    backgroundColor: "#d7ffb9",
    extendedProps: { department: "IT" },
  },
  {
    id: createEventId(),
    title: "Cloud Security Summit",
    start: "2025-02-02",
    textColor: "#ef802b",
    backgroundColor: "#ffd8b6",
    extendedProps: { department: "HR" },
  },
  {
    id: createEventId(),
    title: "Quantum Computing Talk",
    start: "2025-02-02",
    textColor: "#fec001",
    backgroundColor: "#fff0c0",
    extendedProps: { department: "" },
  },
  {
    id: createEventId(),
    title: "Startup Pitch Event",
    start: "2025-02-02",
    textColor: "#559cda",
    backgroundColor: "#deecff",
    extendedProps: { department: "" },
  },
  {
    id: createEventId(),
    title: "Blockchain Insights Forum",
    start: "2025-02-03",
    textColor: "#ff554a",
    backgroundColor: "#ffcbc7",
    extendedProps: { department: "" },
  },
  {
    id: createEventId(),
    title: "Cybersecurity Workshop",
    start: "2025-02-03",
    textColor: "#5a9d27",
    backgroundColor: "#d7ffb9",
    extendedProps: { department: "" },
  },
  {
    id: createEventId(),
    title: "AR/VR Innovations Panel",
    start: "2025-02-03",
    textColor: "#ef802b",
    backgroundColor: "#ffd8b6",
    extendedProps: { department: "" },
  },

  // February 4
  {
    id: createEventId(),
    title: "Cloud Security Summit",
    start: "2025-02-04",
    textColor: "#ef802b",
    backgroundColor: "#ffd8b6",
    extendedProps: { department: "" },
  },
  {
    id: createEventId(),
    title: "Startup Pitch Event",
    start: "2025-02-04",
    textColor: "#fec001",
    backgroundColor: "#fff0c0",
    extendedProps: { department: "" },
  },
  {
    id: createEventId(),
    title: "Cybersecurity Workshop",
    start: "2025-02-04",
    textColor: "#559cda",
    backgroundColor: "#deecff",
    extendedProps: { department: "" },
  },

  // February 5
  {
    id: createEventId(),
    title: "Metaverse Development Forum",
    start: "2025-02-05",
    textColor: "#ff554a",
    backgroundColor: "#ffcbc7",
    extendedProps: { department: "" },
  },
  {
    id: createEventId(),
    title: "Remote Work Strategies",
    start: "2025-02-05",
    textColor: "#5a9d27",
    backgroundColor: "#d7ffb9",
    extendedProps: { department: "" },
  },
  {
    id: createEventId(),
    title: "Digital Marketing Trends",
    start: "2025-02-05",
    textColor: "#ef802b",
    backgroundColor: "#ffd8b6",
    extendedProps: { department: "" },
  },

  // February 6
  {
    id: createEventId(),
    title: "AI in Gaming Conference",
    start: "2025-02-06",
    textColor: "#fec001",
    backgroundColor: "#fff0c0",
    extendedProps: { department: "" },
  },
  {
    id: createEventId(),
    title: "Robotics Engineering Meetup",
    start: "2025-02-06",
    textColor: "#559cda",
    backgroundColor: "#deecff",
    extendedProps: { department: "" },
  },
  {
    id: createEventId(),
    title: "Space Tech Innovations",
    start: "2025-02-06",
    textColor: "#ff554a",
    backgroundColor: "#ffcbc7",
    extendedProps: { department: "" },
  },

  // February 7
  {
    id: createEventId(),
    title: "5G & Future Connectivity",
    start: "2025-02-07",
    textColor: "#5a9d27",
    backgroundColor: "#d7ffb9",
    extendedProps: { department: "" },
  },
  {
    id: createEventId(),
    title: "HealthTech Innovations",
    start: "2025-02-07",
    textColor: "#ef802b",
    backgroundColor: "#ffd8b6",
    extendedProps: { department: "" },
  },
  {
    id: createEventId(),
    title: "EdTech Innovations",
    start: "2025-02-07",
    textColor: "#fec001",
    backgroundColor: "#fff0c0",
    extendedProps: { department: "" },
  },

  // February 8
  {
    id: createEventId(),
    title: "Investor Pitch Night",
    start: "2025-02-08",
    textColor: "#559cda",
    backgroundColor: "#deecff",
    extendedProps: { department: "" },
  },
  {
    id: createEventId(),
    title: "Cyber Resilience Forum",
    start: "2025-02-08",
    textColor: "#ff554a",
    backgroundColor: "#ffcbc7",
    extendedProps: { department: "" },
  },
  {
    id: createEventId(),
    title: "No-Code/Low-Code Revolution",
    start: "2025-02-08",
    textColor: "#5a9d27",
    backgroundColor: "#d7ffb9",
    extendedProps: { department: "" },
  },

  // February 9
  {
    id: createEventId(),
    title: "Tech Disruptors Panel",
    start: "2025-02-09",
    textColor: "#ef802b",
    backgroundColor: "#ffd8b6",
    extendedProps: { department: "" },
  },
  {
    id: createEventId(),
    title: "AI for Social Good",
    start: "2025-02-09",
    textColor: "#fec001",
    backgroundColor: "#fff0c0",
  },
  {
    id: createEventId(),
    title: "Open Source Development",
    start: "2025-02-09",
    textColor: "#559cda",
    backgroundColor: "#deecff",
    extendedProps: { department: "" },
  },

  // February 10
  {
    id: createEventId(),
    title: "Quantum Computing 101",
    start: "2025-02-10",
    textColor: "#ff554a",
    backgroundColor: "#ffcbc7",
    extendedProps: { department: "" },
  },
  {
    id: createEventId(),
    title: "Next-Gen Web Development",
    start: "2025-02-10",
    textColor: "#5a9d27",
    backgroundColor: "#d7ffb9",
    extendedProps: { department: "" },
  },
  {
    id: createEventId(),
    title: "Fintech Innovations",
    start: "2025-02-10",
    textColor: "#ef802b",
    backgroundColor: "#ffd8b6",
    extendedProps: { department: "" },
  },

  // February 11
  {
    id: createEventId(),
    title: "Smart Cities Summit",
    start: "2025-02-11",
    textColor: "#fec001",
    backgroundColor: "#fff0c0",
    extendedProps: { department: "" },
  },
  {
    id: createEventId(),
    title: "Cyber Defense Strategies",
    start: "2025-02-11",
    textColor: "#559cda",
    backgroundColor: "#deecff",
    extendedProps: { department: "" },
  },
  {
    id: createEventId(),
    title: "Ethical AI Debate",
    start: "2025-02-11",
    textColor: "#ff554a",
    backgroundColor: "#ffcbc7",
    extendedProps: { department: "" },
  },

  // February 12
  {
    id: createEventId(),
    title: "Cloud Infrastructure Mastery",
    start: "2025-02-12",
    textColor: "#5a9d27",
    backgroundColor: "#d7ffb9",
    extendedProps: { department: "" },
  },
  {
    id: createEventId(),
    title: "Augmented Reality in Retail",
    start: "2025-02-12",
    textColor: "#ef802b",
    backgroundColor: "#ffd8b6",
    extendedProps: { department: "" },
  },
  {
    id: createEventId(),
    title: "Space Tech & AI",
    start: "2025-02-12",
    textColor: "#fec001",
    backgroundColor: "#fff0c0",
    extendedProps: { department: "" },
  },

  // February 13
  {
    id: createEventId(),
    title: "E-Sports & Gaming Industry Talk",
    start: "2025-02-13",
    textColor: "#559cda",
    backgroundColor: "#deecff",
    extendedProps: { department: "" },
  },
  {
    id: createEventId(),
    title: "MedTech & AI Collaboration",
    start: "2025-02-13",
    textColor: "#ff554a",
    backgroundColor: "#ffcbc7",
    extendedProps: { department: "" },
  },
  {
    id: createEventId(),

    title: "Startup Acceleration Strategies",
    start: "2025-02-13",
    textColor: "#5a9d27",
    backgroundColor: "#d7ffb9",
    extendedProps: { department: "" },
  },

  // February 14
  {
    id: createEventId(),
    title: "Big Data Analytics Conference",
    start: "2025-02-14",
    textColor: "#ef802b",
    backgroundColor: "#ffd8b6",
    extendedProps: { department: "" },
  },
  {
    id: createEventId(),
    title: "Internet of Things (IoT) Meetup",
    start: "2025-02-14",
    textColor: "#fec001",
    backgroundColor: "#fff0c0",
    extendedProps: { department: "" },
  },
  {
    id: createEventId(),
    title: "Digital Privacy & Cyber Ethics",
    start: "2025-02-14",
    textColor: "#559cda",
    backgroundColor: "#deecff",
    extendedProps: { department: "" },
  },

  {
    id: createEventId(),
    title: "All-day event",
    start: todayStr,
    textColor: "#5a9d27",
    backgroundColor: "#d7ffb9",
    extendedProps: { department: "" },
  },
  {
    id: createEventId(),
    title: "Timed event",
    start: todayStr + "T12:00:00",
    textColor: "#fec001",
    backgroundColor: "#fff0c0",
    extendedProps: { department: "" },
  },
  {
    id: createEventId(),
    title: "Sample event",
    start: todayStr + "T12:00:00",
    textColor: "#ff554a",
    backgroundColor: "#ffcbc7",
    extendedProps: { department: "" },
  },
  {
    id: createEventId(),
    title: "Hersvin Development",
    start: "2025-02-18T12:00:00",
    textColor: "#559cda",
    backgroundColor: "#deecff",
    extendedProps: { department: "" },
  },
  {
    id: createEventId(),
    title: "Andrea's Interview",
    start: "2025-02-18",
    textColor: "#ef802b",
    backgroundColor: "#ffd8b6",
    extendedProps: { department: "" },
  },
  {
    id: createEventId(),
    title: "QA's Testing",
    start: "2025-02-18",
    textColor: "#5a9d27",
    backgroundColor: "#d7ffb9",
    extendedProps: { department: "" },
  },
  {
    id: createEventId(),
    title: "PM's Client Visit",
    start: "2025-02-20",
    textColor: "#ff554a",
    backgroundColor: "#ffcbc7",
    extendedProps: { department: "" },
  },
  {
    id: createEventId(),
    title: "Hersvin Dela Cruz Labastida",
    start: "2025-02-20",
    end: "2025-02-21T12:00:00",
    textColor: "#559cda",
    backgroundColor: "#deecff",
    extendedProps: { department: "" },
  },
  {
    id: createEventId(),
    title: "Sample Title Event",
    start: "2025-02-16",
    textColor: "#559cda",
    backgroundColor: "#deecff",
    extendedProps: { department: "" },
  },
];

export function createEventId() {
  return String(eventGuid++);
}
